[package]
name = "geemu_engine"
version = "0.1.0"
edition = "2018"

[dependencies]
geemu_audio = { path = "../geemu_audio"}
png = "0.17.1"

[dependencies.sdl2]
version = "0.34.5"
default-features = false
features = ["static-link", "use-vcpkg", "unsafe_textures"]

[package.metadata.vcpkg]
dependencies = ["sdl2"]
git = "https://github.com/microsoft/vcpkg"
rev = "261c458af6e3eed5d099144aff95d2b5035f656b"

[package.metadata.vcpkg.target]
x86_64-pc-windows-msvc = { triplet = "x64-windows-static-md" }

