[package]
name = "geemu_engine"
version = "0.1.0"
edition = "2018"

[dependencies]
geemu_audio = { path = "../geemu_audio"}
png = "0.17"

[dependencies.sdl2]
version = "0.34"
default-features = false
features = ["static-link", "use-vcpkg", "unsafe_textures"]

